[package]
name = "tesseract-plumbing"
version = "0.1.0"
authors = ["Chris Couzens <ccouzens@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tesseract-sys = "0.5.5"
leptonica-plumbing = { path = "../leptonica-plumbing" }
thiserror = "1.0"

[dev-dependencies]
image = "0.23.14"